/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (unauthenticated) */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One governed generate turn (the platform wire)
         * @description The exact call a delegated agent makes from inside its box. maxTokens is REQUIRED — the gateway reserves worst-case budget against it, so an uncapped turn is unrepresentable on the wire.
         */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anthropic Messages passthrough (the compatibility wire)
         * @description ADR-0028's second wire: unmodified Anthropic clients (Claude Code, @ai-sdk) point their base URL here and get governed inference — verified identity → claim → reserve → Bedrock passthrough → settle. The body is the Anthropic Messages API shape; only the fields the gate needs are constrained here.
         */
        post: operations["anthropicMessages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Self-service inference-grant registration (ADR-0021)
         * @description A service registers its own grant; tenant comes from the verified identity, never the body. 404 when self-service claims are not enabled on this deployment.
         */
        post: operations["createClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            detail?: string;
            reason?: string;
            budget?: {
                [key: string]: unknown;
            };
        };
        GenerateRequest: {
            messages: components["schemas"]["Message"][];
            /** @description Output cap — worst-case budget is reserved against this. */
            maxTokens: number;
            tools?: components["schemas"]["ToolDef"][];
            /** @description Groups turns under one per-session budget cap (ADR-0026). */
            sessionId?: string;
        };
        /** @description One conversation turn on the platform wire. */
        Message: components["schemas"]["UserMessage"] | components["schemas"]["AssistantMessage"] | components["schemas"]["ToolMessage"];
        UserMessage: {
            /** @enum {string} */
            role: "user";
            text: string;
        };
        AssistantMessage: {
            /** @enum {string} */
            role: "assistant";
            text?: string;
            toolCalls?: components["schemas"]["ToolCall"][];
        };
        ToolMessage: {
            /** @enum {string} */
            role: "tool";
            results: components["schemas"]["ToolResult"][];
        };
        ToolCall: {
            id: string;
            name: string;
            input: {
                [key: string]: unknown;
            };
        };
        ToolResult: {
            toolCallId: string;
            content: string;
            isError?: boolean;
        };
        ToolDef: {
            name: string;
            description: string;
            /** @description JSON Schema for the tool input. */
            inputSchema: {
                [key: string]: unknown;
            };
        };
        TokenUsage: {
            inputTokens: number;
            outputTokens: number;
        };
        AssistantTurn: {
            text?: string;
            toolCalls?: components["schemas"]["ToolCall"][];
            usage?: components["schemas"]["TokenUsage"];
        };
        /** @description The Anthropic Messages API request. Permissive by design — the gateway passes it through; only the budget-relevant fields are required. */
        AnthropicMessagesRequest: {
            model: string;
            max_tokens: number;
            messages: Record<string, never>[];
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description The request shape failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or unverifiable credential (fail closed). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The upstream model call failed. */
        InferenceFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gateway is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ok";
                    };
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description The assistant's turn, with metered usage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantTurn"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Budget exceeded — the reserve step refused admission. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InferenceFailed"];
        };
    };
    anthropicMessages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnthropicMessagesRequest"];
            };
        };
        responses: {
            /** @description The Anthropic-shaped response, passed through. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Budget exceeded. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InferenceFailed"];
        };
    };
    createClaim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description The claim as stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Self-service claims not enabled here. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
